version: '3.9'
name: fhh-vrvis-backend
services:
  dev:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspace
    command: sleep infinity
    ports:
      - 3001:3001
    environment:
      NODE_ENV: development
    networks:
      - fhh-vrvis-net

networks:
  fhh-vrvis-net:
    external: true
